apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"tekton.dev/v1beta1","kind":"Task","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"globex-ui-pipeline"},"name":"update-manifest","namespace":"software-supply-chain"},"spec":{"description":"This
      task updates the manifest for the current application to point to the
      image tag created with the short commit.","params":[{"description":"Used
      to tag the built
      image.","name":"image","type":"string"},{"default":"main","description":"Target
      branch to push
      to","name":"target-branch","type":"string"},{"default":"Tekton
      Pipeline","description":"Git user name for performing the push
      operation.","name":"git_user_name","type":"string"},{"default":"tekton@tekton.com","description":"Git
      user email for performing the push
      operation.","name":"git_user_email","type":"string"},{"description":"File
      in which the image configuration is
      stored.","name":"configuration_file","type":"string"},{"description":"Repo
      in which the image configuration is
      stored.","name":"repository","type":"string"}],"steps":[{"image":"alpine/git:latest","name":"git","script":"#
      Setting up the git config.\ngit config --global user.email
      \"$(params.git_user_email)\"\ngit config --global user.name
      \"$(params.git_user_name)\"\n# Checkout target branch to avoid the
      detached HEAD state\nTMPDIR=$(mktemp -d)\ncd $TMPDIR\ngit clone
      $(params.repository)\ncd secured-supply-chain-black-hat\ngit checkout
      $(params.target-branch)\n# Set to the short commit value passed as
      parameter.\n# Notice the enclosing \" to keep it as a string in the
      resulting YAML.\nIMAGE=\\\"$(params.image)\\\"\nsed -i
      \"s#\\(.*value:\\s*\\).*#\\1 ${IMAGE}#\" $(params.configuration_file)\ngit
      add $(params.configuration_file)\ngit commit -m \"Automatically updated
      manifest to point to image tag $IMAGE\"\ngit push origin
      $(params.target-branch)      \n"}]}}
  resourceVersion: '45775'
  name: update-manifest
  uid: 54758130-afa8-4983-bd92-12466d7b08e5
  creationTimestamp: '2024-09-30T18:59:27Z'
  generation: 1
  managedFields:
    - apiVersion: tekton.dev/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:kubectl.kubernetes.io/last-applied-configuration': {}
          'f:labels':
            .: {}
            'f:app.kubernetes.io/instance': {}
        'f:spec':
          .: {}
          'f:description': {}
          'f:params': {}
          'f:steps': {}
      manager: argocd-application-controller
      operation: Update
      time: '2024-09-30T18:59:27Z'
  namespace: software-supply-chain
  labels:
    app.kubernetes.io/instance: globex-ui-pipeline
spec:
  description: >-
    This task updates the manifest for the current application to point to the
    image tag created with the short commit.
  params:
    - description: Used to tag the built image.
      name: image
      type: string
    - default: main
      description: Target branch to push to
      name: target-branch
      type: string
    - default: Tekton Pipeline
      description: Git user name for performing the push operation.
      name: git_user_name
      type: string
    - default: tekton@tekton.com
      description: Git user email for performing the push operation.
      name: git_user_email
      type: string
    - description: File in which the image configuration is stored.
      name: configuration_file
      type: string
    - description: Repo in which the image configuration is stored.
      name: repository
      type: string
  steps:
    - image: 'alpine/git:latest'
      name: git
      resources: {}
      script: >
        # Setting up the git config.

        git config --global user.email "$(params.git_user_email)"

        git config --global user.name "$(params.git_user_name)"

        # Checkout target branch to avoid the detached HEAD state

        TMPDIR=$(mktemp -d)

        cd $TMPDIR

        git clone $(params.repository)

        cd secured-supply-chain-black-hat

        git checkout $(params.target-branch)

        # Set to the short commit value passed as parameter.

        # Notice the enclosing " to keep it as a string in the resulting YAML.

        IMAGE=\"$(params.image)\"

        sed -i "s#\(.*value:\s*\).*#\1 ${IMAGE}#" $(params.configuration_file)

        git add $(params.configuration_file)

        git commit -m "Automatically updated manifest to point to image tag
        $IMAGE"

        git push origin $(params.target-branch)      
